/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  safelist: [
    "border-node-input", "bg-node-input/10", "text-node-input",
    "border-node-cron", "bg-node-cron/10", "text-node-cron",
    "border-node-llm", "bg-node-llm/10", "text-node-llm",
    "border-node-agent", "bg-node-agent/10", "text-node-agent",
    "border-node-codex", "bg-node-codex/10", "bg-node-codex/12", "text-node-codex",
    "border-node-condition", "bg-node-condition/10", "text-node-condition",
    "border-node-switch", "bg-node-switch/10", "text-node-switch",
    "border-node-execute", "bg-node-execute/10", "text-node-execute",
    "border-node-output", "bg-node-output/10", "text-node-output",
    "border-node-http", "bg-node-http/10", "text-node-http",
    "border-node-sticky", "bg-node-sticky/10", "text-node-sticky",
    "border-node-merge", "bg-node-merge/10", "text-node-merge",
    "border-node-set", "bg-node-set/10", "text-node-set",
    "border-node-slack", "bg-node-slack/10", "text-node-slack",
    "border-node-discord", "bg-node-discord/10", "text-node-discord",
    "border-node-telegram", "bg-node-telegram/10", "text-node-telegram",
    "border-node-email", "bg-node-email/10", "text-node-email",
    "border-node-error", "bg-node-error/10", "text-node-error",
    "border-node-variable", "bg-node-variable/10", "text-node-variable",
    "border-node-loop", "bg-node-loop/10", "text-node-loop",
    "border-node-wait", "bg-node-wait/10", "text-node-wait",
    "border-node-disable", "bg-node-disable/10", "text-node-disable",
    "border-node-redis", "bg-node-redis/10", "text-node-redis",
    "border-node-rag", "bg-node-rag/10", "text-node-rag",
    "border-node-grist", "bg-node-grist/10", "text-node-grist",
    "border-node-throw-error", "bg-node-throw-error/10", "text-node-throw-error",
    "border-node-rabbitmq", "bg-node-rabbitmq/10", "text-node-rabbitmq",
    "border-node-crawler", "bg-node-crawler/10", "text-node-crawler",
    "border-node-console-log", "bg-node-console-log/10", "text-node-console-log",
    "border-node-playwright", "bg-node-playwright/10", "text-node-playwright",
    "bg-node-loop/20", "text-node-loop-loop", "text-node-loop-done",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          blue: "hsl(var(--accent-blue))",
          red: "hsl(var(--accent-red))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        glow: {
          purple: "hsl(var(--glow-purple))",
          blue: "hsl(var(--glow-blue))",
          red: "hsl(var(--glow-red))",
        },
        node: {
          input: "hsl(var(--node-input))",
          cron: "hsl(var(--node-cron))",
          llm: "hsl(var(--node-llm))",
          agent: "hsl(var(--node-agent))",
          codex: "hsl(var(--node-codex))",
          condition: "hsl(var(--node-condition))",
          switch: "hsl(var(--node-switch))",
          execute: "hsl(var(--node-execute))",
          output: "hsl(var(--node-output))",
          http: "hsl(var(--node-http))",
          sticky: "hsl(var(--node-sticky))",
          merge: "hsl(var(--node-merge))",
          set: "hsl(var(--node-set))",
          slack: "hsl(var(--node-slack))",
          discord: "hsl(var(--node-discord))",
          telegram: "hsl(var(--node-telegram))",
          email: "hsl(var(--node-email))",
          error: "hsl(var(--node-error))",
          variable: "hsl(var(--node-variable))",
          loop: {
            DEFAULT: "hsl(var(--node-loop))",
            loop: "hsl(142 76% 36%)",
            done: "hsl(221 83% 53%)",
          },
          wait: "hsl(var(--node-wait))",
          disable: "hsl(var(--node-disable))",
          redis: "hsl(var(--node-redis))",
          rag: "hsl(var(--node-rag))",
          grist: "hsl(var(--node-grist))",
          "throw-error": "hsl(var(--node-throw-error))",
          rabbitmq: "hsl(var(--node-rabbitmq))",
          crawler: "hsl(var(--node-crawler))",
          "console-log": "hsl(var(--node-console-log))",
          playwright: "hsl(var(--node-playwright))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "calc(var(--radius) + 4px)",
        "2xl": "calc(var(--radius) + 8px)",
      },
      fontFamily: {
        sans: ["Geist", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        "gradient-metallic": "linear-gradient(135deg, hsl(var(--primary)) 0%, hsl(var(--accent-blue)) 50%, hsl(var(--accent-red)) 100%)",
        "gradient-primary": "linear-gradient(135deg, hsl(var(--primary)) 0%, hsl(270 80% 50%) 100%)",
        "gradient-surface": "linear-gradient(145deg, hsl(var(--card)) 0%, hsl(240 12% 6%) 100%)",
        "shimmer": "linear-gradient(90deg, transparent 0%, hsl(var(--primary) / 0.1) 50%, transparent 100%)",
      },
      boxShadow: {
        "glow-sm": "0 0 10px hsl(var(--primary) / 0.3)",
        "glow-md": "0 0 20px hsl(var(--primary) / 0.4), 0 0 40px hsl(var(--primary) / 0.1)",
        "glow-lg": "0 0 30px hsl(var(--primary) / 0.5), 0 0 60px hsl(var(--primary) / 0.2)",
        "glow-purple": "0 0 20px hsl(var(--glow-purple) / 0.3), 0 0 40px hsl(var(--glow-purple) / 0.1)",
        "glow-blue": "0 0 20px hsl(var(--glow-blue) / 0.3), 0 0 40px hsl(var(--glow-blue) / 0.1)",
        "glow-red": "0 0 20px hsl(var(--glow-red) / 0.3), 0 0 40px hsl(var(--glow-red) / 0.1)",
        "metallic": "0 8px 32px hsl(0 0% 0% / 0.3), 0 2px 8px hsl(0 0% 0% / 0.2), inset 0 1px 0 0 hsl(0 0% 100% / 0.03)",
        "metallic-hover": "0 12px 40px hsl(0 0% 0% / 0.4), 0 4px 12px hsl(0 0% 0% / 0.2), 0 0 20px hsl(var(--primary) / 0.15)",
        "elevated": "0 4px 6px -1px hsl(0 0% 0% / 0.2), 0 2px 4px -2px hsl(0 0% 0% / 0.2)",
        "inner-glow": "inset 0 1px 0 0 hsl(0 0% 100% / 0.05)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        "fade-in": {
          from: { opacity: 0 },
          to: { opacity: 1 },
        },
        "fade-out": {
          from: { opacity: 1 },
          to: { opacity: 0 },
        },
        "slide-in": {
          from: { transform: "translateY(10px)", opacity: 0 },
          to: { transform: "translateY(0)", opacity: 1 },
        },
        "slide-up": {
          from: { transform: "translateY(100%)", opacity: 0 },
          to: { transform: "translateY(0)", opacity: 1 },
        },
        "slide-down": {
          from: { transform: "translateY(-10px)", opacity: 0 },
          to: { transform: "translateY(0)", opacity: 1 },
        },
        "scale-in": {
          from: { transform: "scale(0.95)", opacity: 0 },
          to: { transform: "scale(1)", opacity: 1 },
        },
        "scale-out": {
          from: { transform: "scale(1)", opacity: 1 },
          to: { transform: "scale(0.95)", opacity: 0 },
        },
        pulse: {
          "0%, 100%": { opacity: 1 },
          "50%": { opacity: 0.5 },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        glow: {
          "0%, 100%": {
            boxShadow: "0 0 5px hsl(var(--primary) / 0.2), 0 0 10px hsl(var(--primary) / 0.1)"
          },
          "50%": {
            boxShadow: "0 0 15px hsl(var(--primary) / 0.4), 0 0 30px hsl(var(--primary) / 0.2)"
          },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-5px)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: 0.5 },
          "50%": { opacity: 1 },
        },
        "gradient-shift": {
          "0%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
        "border-pulse": {
          "0%, 100%": { borderColor: "hsl(var(--border))" },
          "50%": { borderColor: "hsl(var(--primary) / 0.5)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "fade-out": "fade-out 0.3s ease-out",
        "slide-in": "slide-in 0.3s ease-out",
        "slide-up": "slide-up 0.4s ease-out",
        "slide-down": "slide-down 0.3s ease-out",
        "scale-in": "scale-in 0.2s ease-out",
        "scale-out": "scale-out 0.2s ease-out",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        shimmer: "shimmer 2s infinite",
        glow: "glow 2s ease-in-out infinite alternate",
        float: "float 3s ease-in-out infinite",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        "gradient-shift": "gradient-shift 3s ease infinite",
        "border-pulse": "border-pulse 2s ease-in-out infinite",
      },
      transitionDuration: {
        "400": "400ms",
      },
      backdropBlur: {
        xs: "2px",
      },
    },
  },
  plugins: [],
};
