import type { NodeType } from "./workflow";

export interface NodeDefinition {
  type: NodeType;
  label: string;
  description: string;
  color: string;
  icon: string;
  inputs: number;
  outputs: number;
  /** Display override for inputs (e.g. "n" for variable) */
  inputsDisplay?: string;
  /** Display override for outputs (e.g. "n" for variable) */
  outputsDisplay?: string;
  defaultData: { label: string } & Record<string, unknown>;
}

export const NODE_DEFINITIONS: Record<NodeType, NodeDefinition> = {
  textInput: {
    type: "textInput",
    label: "Input",
    description: "Text entry point for the workflow",
    color: "node-input",
    icon: "Type",
    inputs: 0,
    outputs: 1,
    defaultData: {
      label: "start",
      value: "",
      inputFields: [{ key: "text" }],
    },
  },
  cron: {
    type: "cron",
    label: "Cron",
    description: "Trigger a workflow on a schedule",
    color: "node-cron",
    icon: "CalendarClock",
    inputs: 0,
    outputs: 1,
    defaultData: {
      label: "cron",
      cronExpression: "0 * * * *",
    },
  },
  telegramTrigger: {
    type: "telegramTrigger",
    label: "Telegram Trigger",
    description: "Receive Telegram bot webhook updates",
    color: "node-telegram",
    icon: "MessageSquare",
    inputs: 0,
    outputs: 1,
    defaultData: {
      label: "telegramTrigger",
      credentialId: "",
    },
  },
  websocketTrigger: {
    type: "websocketTrigger",
    label: "WebSocket Trigger",
    description: "Connect to an external WebSocket and trigger on events",
    color: "node-websocket",
    icon: "Radio",
    inputs: 0,
    outputs: 1,
    defaultData: {
      label: "websocketTrigger",
      websocketUrl: "",
      websocketHeaders: "",
      websocketSubprotocols: "",
      websocketTriggerEvents: ["onMessage"],
      retryEnabled: true,
      retryWaitSeconds: 5,
    },
  },
  output: {
    type: "output",
    label: "Output",
    description: "Output endpoint for the workflow",
    color: "node-output",
    icon: "FileJson",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "output",
      message: "$input.text",
      allowDownstream: false,
    },
  },
  llm: {
    type: "llm",
    label: "LLM",
    description: "Process text with a language model",
    color: "node-llm",
    icon: "Brain",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "llm",
      model: "",
      temperature: 0.7,
      systemInstruction: "",
      userMessage: "$input.text",
      requestTimeoutSeconds: 60,
      batchModeEnabled: false,
      outputType: "text",
      imageInputEnabled: false,
      imageInput: "",
      jsonOutputEnabled: false,
      jsonOutputSchema: "",
      guardrailsEnabled: false,
      guardrailsCategories: [],
      guardrailsSeverity: "medium",
      fallbackCredentialId: "",
      fallbackModel: "",
    },
  },
  agent: {
    type: "agent",
    label: "AI Agent",
    description: "LLM with tool calling - run Python tools",
    color: "node-agent",
    icon: "Bot",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "agent",
      model: "",
      temperature: 0.7,
      systemInstruction: "",
      userMessage: "$input.text",
      tools: [],
      mcpConnections: [],
      skills: [],
      toolTimeoutSeconds: 30,
      requestTimeoutSeconds: 60,
      maxToolIterations: 30,
      imageInputEnabled: false,
      imageInput: "",
      isOrchestrator: false,
      subAgentLabels: [],
      subWorkflowIds: [],
      hitlEnabled: false,
      hitlSummary: "",
      jsonOutputEnabled: false,
      jsonOutputSchema: "",
      guardrailsEnabled: false,
      guardrailsCategories: [],
      guardrailsSeverity: "medium",
      fallbackCredentialId: "",
      fallbackModel: "",
      persistentMemoryEnabled: false,
    },
  },
  condition: {
    type: "condition",
    label: "Condition",
    description: "Branch workflow based on if condition",
    color: "node-condition",
    icon: "GitBranch",
    inputs: 1,
    outputs: 2,
    defaultData: {
      label: "condition",
      condition: "$input.text.length > 0",
    },
  },
  switch: {
    type: "switch",
    label: "Switch",
    description: "Route execution by matching a value",
    color: "node-switch",
    icon: "Shuffle",
    inputs: 1,
    outputs: 3,
    inputsDisplay: "1",
    outputsDisplay: "n",
    defaultData: {
      label: "switch",
      expression: "$input.text",
      cases: ["case1", "case2"],
    },
  },
  wait: {
    type: "wait",
    label: "Wait",
    description: "Delay execution for specified time",
    color: "node-wait",
    icon: "Clock",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "wait",
      duration: 1000,
    },
  },
  execute: {
    type: "execute",
    label: "Execute",
    description: "Transform and pass input to downstream nodes",
    color: "node-execute",
    icon: "Play",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "execute",
      executeInput: "$input.text",
    },
  },
  http: {
    type: "http",
    label: "HTTP",
    description: "Make an HTTP request using cURL",
    color: "node-http",
    icon: "Globe",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "httpRequest",
      curl: "curl -X GET https://api.example.com",
    },
  },
  websocketSend: {
    type: "websocketSend",
    label: "WebSocket Send",
    description: "Connect to an external WebSocket and send a message",
    color: "node-websocket",
    icon: "Send",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "websocketSend",
      websocketUrl: "",
      websocketHeaders: "",
      websocketSubprotocols: "",
      websocketMessage: "$input",
    },
  },
  sticky: {
    type: "sticky",
    label: "Sticky Note",
    description: "Add markdown notes to the canvas",
    color: "node-sticky",
    icon: "StickyNote",
    inputs: 0,
    outputs: 0,
    defaultData: {
      label: "stickyNote",
      stickyTitle: "Sticky Note",
      stickyColor: "yellow",
      note: "Double click to edit",
    },
  },
  merge: {
    type: "merge",
    label: "Merge",
    description: "Wait for multiple inputs and merge them",
    color: "node-merge",
    icon: "GitMerge",
    inputs: 2,
    outputs: 1,
    inputsDisplay: "n",
    outputsDisplay: "1",
    defaultData: {
      label: "merge",
      inputCount: 2,
    },
  },
  set: {
    type: "set",
    label: "Set",
    description: "Transform and map input data to custom output",
    color: "node-set",
    icon: "Settings2",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "set",
      mappings: [{ key: "text", value: "$input.text" }],
    },
  },
  jsonOutputMapper: {
    type: "jsonOutputMapper",
    label: "JSON output mapper",
    description:
      "Build JSON from key-value mappings; as the only terminal, webhook and run return that object without label or result wrapping",
    color: "node-output",
    icon: "Braces",
    inputs: 1,
    outputs: 0,
    defaultData: {
      label: "jsonResponse",
      mappings: [{ key: "message", value: "$input.text" }],
    },
  },
  slack: {
    type: "slack",
    label: "Slack",
    description: "Send a message to Slack via webhook",
    color: "node-slack",
    icon: "MessageSquare",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "slack",
      credentialId: "",
      message: "$input.text",
    },
  },
  discord: {
    type: "discord",
    label: "Discord",
    description: "Send a message to Discord via webhook",
    color: "node-discord",
    icon: "MessageSquare",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "discord",
      credentialId: "",
      message: "$input.text",
      username: "",
      avatarUrl: "",
    },
  },
  telegram: {
    type: "telegram",
    label: "Telegram",
    description: "Send a Telegram bot message",
    color: "node-telegram",
    icon: "MessageSquare",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "telegram",
      credentialId: "",
      chatId: "",
      message: "$input.text",
    },
  },
  slackTrigger: {
    type: "slackTrigger",
    label: "Slack Trigger",
    description: "Receive Slack events and trigger the workflow",
    color: "node-slack",
    icon: "MessageSquare",
    inputs: 0,
    outputs: 1,
    defaultData: {
      label: "slackTrigger",
      credentialId: "",
    },
  },
  discordTrigger: {
    type: "discordTrigger",
    label: "Discord Trigger",
    description: "Receive Discord interactions and trigger the workflow",
    color: "node-discord",
    icon: "MessageSquare",
    inputs: 0,
    outputs: 1,
    defaultData: {
      label: "discordTrigger",
      credentialId: "",
    },
  },
  imapTrigger: {
    type: "imapTrigger",
    label: "IMAP Trigger",
    description: "Poll an IMAP inbox for new emails",
    color: "node-email",
    icon: "Inbox",
    inputs: 0,
    outputs: 1,
    defaultData: {
      label: "imapTrigger",
      credentialId: "",
      pollIntervalMinutes: 5,
    },
  },
  sendEmail: {
    type: "sendEmail",
    label: "Send Email",
    description: "Send an email via SMTP",
    color: "node-email",
    icon: "Mail",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "sendEmail",
      credentialId: "",
      to: "",
      subject: "",
      emailBody: "$input.text",
    },
  },
  errorHandler: {
    type: "errorHandler",
    label: "Error Handler",
    description: "Run this flow when a node errors",
    color: "node-error",
    icon: "AlertTriangle",
    inputs: 0,
    outputs: 1,
    defaultData: {
      label: "errorHandler",
      message: "$error.message",
    },
  },
  variable: {
    type: "variable",
    label: "Variable",
    description: "Set or update a variable value",
    color: "node-variable",
    icon: "Variable",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "variable",
      variableName: "myVariable",
      variableValue: "$input.text",
      variableType: "auto",
      isGlobal: false,
    },
  },
  loop: {
    type: "loop",
    label: "Loop",
    description: "Iterate over an array of items",
    color: "node-loop",
    icon: "Repeat",
    inputs: 1,
    outputs: 2,
    defaultData: {
      label: "loop",
      arrayExpression: "$input.items",
    },
  },
  disableNode: {
    type: "disableNode",
    label: "Disable Node",
    description: "Disable another node in the workflow",
    color: "node-disable",
    icon: "Ban",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "disableNode",
      targetNodeLabel: "",
    },
  },
  redis: {
    type: "redis",
    label: "Redis",
    description: "Perform Redis operations",
    color: "node-redis",
    icon: "Database",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "redis",
      credentialId: "",
      redisOperation: undefined,
      redisKey: "$input.text",
      redisValue: "$input.text",
      redisTtl: undefined,
    },
  },
  rag: {
    type: "rag",
    label: "Qdrant RAG",
    description: "Insert or search documents in Qdrant vector store",
    color: "node-rag",
    icon: "Search",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "rag",
      vectorStoreId: "",
      ragOperation: undefined,
      documentContent: "$input.text",
      documentMetadata: "{}",
      queryText: "$input.text",
      searchLimit: 5,
      metadataFilters: "{}",
    },
  },
  grist: {
    type: "grist",
    label: "Grist",
    description: "Read, write, and manage data in Grist spreadsheets",
    color: "node-grist",
    icon: "Table2",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "grist",
      credentialId: "",
      gristOperation: undefined,
      gristDocId: "",
      gristTableId: "",
      gristRecordId: "",
      gristRecordData: "{}",
      gristRecordsData: "[]",
      gristFilter: "{}",
      gristSort: "",
      gristLimit: 100,
      gristRecordIds: "[]",
      gristRecordDataInputMode: "raw",
      gristFilterInputMode: "raw",
    },
  },
  googleSheets: {
    type: "googleSheets",
    label: "Google Sheets",
    description: "Read, write, append and update Google Sheets via OAuth2",
    color: "node-google-sheets",
    icon: "Sheet",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "googleSheets",
      credentialId: "",
      gsOperation: undefined as string | undefined,
      gsSpreadsheetId: "",
      gsSheetName: "Sheet1",
      gsStartRow: "1",
      gsUpdateRow: "1",
      gsMaxRows: "0",
      gsHasHeader: true,
      gsRange: "A1:Z100",
      gsKeepHeader: false,
      gsAppendPlacement: "append",
      gsValuesInputMode: "raw",
      gsValuesSelectiveRows: "1",
      gsValuesSelectiveCols: "3",
      gsValues: "[]",
    },
  },
  dataTable: {
    type: "dataTable",
    label: "DataTable",
    description: "Read, write, and manage data in Heym DataTables",
    color: "node-datatable",
    icon: "Table2",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "dataTable",
      dataTableId: "",
      dataTableOperation: undefined,
      dataTableFilter: "{}",
      dataTableData: "{}",
      dataTableRowId: "",
      dataTableLimit: 100,
      dataTableSort: "",
    },
  },
  throwError: {
    type: "throwError",
    label: "Throw Error",
    description: "Stop workflow execution and return an error response",
    color: "node-throw-error",
    icon: "XCircle",
    inputs: 1,
    outputs: 0,
    defaultData: {
      label: "throwError",
      errorMessage: "$input.text",
      httpStatusCode: 400,
    },
  },
  rabbitmq: {
    type: "rabbitmq",
    label: "RabbitMQ",
    description: "Send or receive messages from RabbitMQ queues",
    color: "node-rabbitmq",
    icon: "Rabbit",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "rabbitmq",
      credentialId: "",
      rabbitmqOperation: undefined,
      rabbitmqExchange: "",
      rabbitmqRoutingKey: "",
      rabbitmqQueueName: "",
      rabbitmqMessageBody: "$input",
      rabbitmqDelayMs: undefined,
    },
  },
  crawler: {
    type: "crawler",
    label: "Crawler",
    description: "Scrape web pages using FlareSolverr with optional HTML extraction",
    color: "node-crawler",
    icon: "Bug",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "crawler",
      credentialId: "",
      crawlerUrl: "$input.text",
      crawlerWaitSeconds: 0,
      crawlerMaxTimeout: 60000,
      crawlerMode: "basic",
      crawlerSelectors: [],
    },
  },
  consoleLog: {
    type: "consoleLog",
    label: "Console Log",
    description: "Log value to backend (server) console",
    color: "node-console-log",
    icon: "Terminal",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "consoleLog",
      logMessage: "$input",
    },
  },
  playwright: {
    type: "playwright",
    label: "Playwright",
    description: "Browser automation with configurable steps",
    color: "node-playwright",
    icon: "MonitorPlay",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "playwright",
      playwrightSteps: [],
      playwrightCode: "",
      playwrightHeadless: true,
      playwrightTimeout: 30000,
      playwrightCaptureNetwork: false,
      playwrightAuthEnabled: false,
      playwrightAuthStateExpression: "",
      playwrightAuthCheckSelector: "",
      playwrightAuthCheckTimeout: 5000,
      playwrightAuthFallbackSteps: [],
    },
  },
  drive: {
    type: "drive",
    label: "Drive",
    description: "List and manage Drive files: get, delete, password, TTL, max downloads",
    color: "node-drive",
    icon: "HardDrive",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "drive",
      driveOperation: undefined,
      driveFileId: "",
    },
  },
  bigquery: {
    type: "bigquery",
    label: "BigQuery",
    description: "Run SQL queries and insert rows into Google BigQuery",
    color: "node-google-sheets",
    icon: "Database",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "bigquery",
      credentialId: "",
      bqOperation: undefined as string | undefined,
      bqProjectId: "",
      bqQuery: "",
      bqMaxResults: "1000",
      bqDatasetId: "",
      bqTableId: "",
      bqRowsInputMode: "raw",
      bqRows: "[]",
      bqMappings: [{ key: "field", value: "$input.text" }],
    },
  },
  mcpCall: {
    type: "mcpCall",
    label: "MCP Call",
    description: "Call a specific MCP tool directly — no LLM required",
    color: "node-agent",
    icon: "Plug",
    inputs: 1,
    outputs: 1,
    defaultData: {
      label: "mcpCall",
      connection: {
        id: "",
        transport: "sse" as const,
        label: "",
        timeoutSeconds: 30,
        url: "",
        headers: {},
      },
      selectedTool: "",
      toolArguments: {} as Record<string, string>,
      timeoutSeconds: 30,
    },
  },
};
