import { expect, test } from "@playwright/test";

import {
  acceptNextDialog,
  clearDriveFiles,
  prepareAuthenticatedPage,
  uploadDriveFile,
} from "./support";

// These tests share one account's Drive and assert on its global empty state,
// so they must not run concurrently with each other under --fully-parallel.
test.describe.configure({ mode: "serial" });

test.beforeEach(async ({ page }) => {
  await prepareAuthenticatedPage(page);
});

test("shows the empty state when Drive has no files", async ({ page }) => {
  await clearDriveFiles(page);

  await page.goto("/?tab=drive");
  const main = page.getByRole("main");
  await expect(main.getByRole("heading", { name: "Drive", exact: true })).toBeVisible();
  await expect(main.getByText("No files yet", { exact: true })).toBeVisible();
  await expect(main.getByText("Files generated by skills will appear here")).toBeVisible();
});

test("lists an uploaded file, filters it via search, and deletes it", async ({ page }) => {
  await clearDriveFiles(page);
  const filename = `e2e-report-${Date.now()}.txt`;
  await uploadDriveFile(page, filename, "playwright drive contents");

  await page.goto("/?tab=drive");
  const main = page.getByRole("main");

  // The uploaded file is listed.
  await expect(main.getByText(filename)).toBeVisible();

  // Search filters the list down to matching files.
  const search = page.getByPlaceholder("Search files...");
  await search.fill("definitely-not-this-file");
  await expect(main.getByText(filename)).toBeHidden();
  await search.fill(filename.slice(0, 10));
  await expect(main.getByText(filename)).toBeVisible();

  // Delete the file (confirm dialog) and fall back to the empty state.
  await search.fill("");
  await acceptNextDialog(
    page,
    () => page.getByTitle("Delete").click(),
    `Delete "${filename}"? This cannot be undone.`,
  );
  await expect(main.getByText(filename)).toBeHidden();
  await expect(main.getByText("No files yet", { exact: true })).toBeVisible();
});
