import {
  AlertTriangle,
  Ban,
  BarChart3,
  Bot,
  Brain,
  Braces,
  Bug,
  CalendarClock,
  Clock,
  Database,
  FileJson,
  GitBranch,
  GitMerge,
  Globe,
  Github,
  HardDrive,
  Inbox,
  Mail,
  MessageSquare,
  MonitorPlay,
  Play,
  Plug,
  Rabbit,
  Radio,
  Repeat,
  Search,
  Send,
  Server,
  Settings2,
  Sheet,
  Shuffle,
  StickyNote,
  Table2,
  Terminal,
  Type,
  Variable,
  XCircle,
} from "lucide-vue-next";

import type { NodeType } from "@/types/workflow";

export const nodeIcons: Record<NodeType, ReturnType<typeof Type>> = {
  textInput: Type,
  cron: CalendarClock,
  telegramTrigger: MessageSquare,
  websocketTrigger: Radio,
  llm: Brain,
  agent: Bot,
  condition: GitBranch,
  switch: Shuffle,
  execute: Play,
  output: FileJson,
  wait: Clock,
  http: Globe,
  websocketSend: Send,
  sticky: StickyNote,
  merge: GitMerge,
  set: Settings2,
  jsonOutputMapper: Braces,
  chartOutput: BarChart3,
  telegram: MessageSquare,
  slack: MessageSquare,
  slackTrigger: MessageSquare,
  discord: MessageSquare,
  discordTrigger: MessageSquare,
  sendEmail: Mail,
  errorHandler: AlertTriangle,
  variable: Variable,
  loop: Repeat,
  disableNode: Ban,
  redis: Database,
  rag: Search,
  grist: Table2,
  github: Github,
  googleSheets: Sheet,
  bigquery: Database,
  supabase: Database,
  dataTable: Table2,
  throwError: XCircle,
  rabbitmq: Rabbit,
  imapTrigger: Inbox,
  crawler: Bug,
  consoleLog: Terminal,
  playwright: MonitorPlay,
  drive: HardDrive,
  s3: Server,
  mcpCall: Plug,
};

/** Tailwind text-* classes aligned with canvas node header tints (BaseNode). */
export const nodeIconColorClass: Record<NodeType, string> = {
  chartOutput: "text-node-output",
  textInput: "text-node-input",
  cron: "text-node-cron",
  telegramTrigger: "text-node-telegram",
  websocketTrigger: "text-node-websocket",
  llm: "text-node-llm",
  agent: "text-node-agent",
  condition: "text-node-condition",
  switch: "text-node-switch",
  execute: "text-node-execute",
  output: "text-node-output",
  wait: "text-node-wait",
  http: "text-node-http",
  websocketSend: "text-node-websocket",
  sticky: "text-node-sticky",
  merge: "text-node-merge",
  set: "text-node-set",
  jsonOutputMapper: "text-node-output",
  telegram: "text-node-telegram",
  slack: "text-node-slack",
  slackTrigger: "text-node-slack",
  discord: "text-node-discord",
  discordTrigger: "text-node-discord",
  sendEmail: "text-node-email",
  errorHandler: "text-node-error",
  variable: "text-node-variable",
  loop: "text-node-loop",
  disableNode: "text-node-disable",
  redis: "text-node-redis",
  rag: "text-node-rag",
  grist: "text-node-grist",
  github: "text-node-github",
  googleSheets: "text-node-google-sheets",
  bigquery: "text-node-google-sheets",
  supabase: "text-node-datatable",
  dataTable: "text-node-datatable",
  throwError: "text-node-throw-error",
  rabbitmq: "text-node-rabbitmq",
  imapTrigger: "text-node-email",
  crawler: "text-node-crawler",
  consoleLog: "text-node-console-log",
  playwright: "text-node-playwright",
  drive: "text-node-drive",
  s3: "text-node-drive",
  mcpCall: "text-node-agent",
};
